[package]
name = "scs_client"
version = "0.1.0"
authors = ["Mark Kirichenko <atanzuuu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socket2 = "0.4.0"
